# Questions
questions = [
    "What is the primary function of a CPU?",
    "Which of the following is NOT a type of computer memory?",
    "Which programming language is renowned for its readability and simplicity?",
    "What does IDE stand for in the context of programming?",
    "What file extension is commonly used for Python files?",
    "What is the purpose of the 'if' statement in Python?",
    "Which of the following is used to indicate a single-line comment in Python?",
    "What does HTML stand for?",
    "What is the purpose of a 'for' loop in Python?",
    "Which of the following is a data type in Python?",
    "What symbol is used for exponentiation in Python?",
    "Which function is used to read input from the user in Python?",
    "Which of the following is NOT a valid Python variable name?",
    "Which operator is used for floor division in Python?",
    "What is the output of 2 + 3 * 5?",
    "Which of the following data structures stores elements in key-value pairs?",
    "What does the 'len()' function in Python return?",
    "Which of the following is used to import a module in Python?",
    "What does the 'append()' method do in Python lists?",
    "What is Python?",
    "Which of the following statements is true about Python?",
    "Which of the following is an immutable data type in Python?",
    "What is the output of print(\"Python\"[1:4])?",
    "What is the output of print(\"Python\".upper())?",
    "What does the pass statement do in Python?",
    "Which of the following is an incorrect variable name in Python?",
    "What is the output of print(10 // 3)?",
    "Which of the following is not a valid way to start a comment in Python?",
    "What is the output of print(\"Python\".find(\"th\"))?",
    "What does the continue statement do in Python?",
    "What is the output of print(5 != 6)?",
    "Which of the following is a valid way to create a dictionary in Python?",
    "What is the output of print(\"python\".capitalize())?",
    "How do you convert a string to a list in Python?",
    "What does the % operator do in Python?",
    "Which function is used to concatenate two lists in Python?"
]

# Choices
choices = [
    ["A) Storing data", "B) Processing instructions", "C) Providing power"],
    ["A) RAM", "B) ROM", "C) CPU"],
    ["A) C++", "B) Python", "C) Java"],
    ["A) Integrated Development Environment", "B) Internet Development Environment", "C) Integrated Design Environment"],
    ["A) .py", "B) .java", "C) .cpp"],
    ["A) Iterating over a sequence", "B) Executing code based on conditions", "C) Defining a function"],
    ["A) //", "B) --", "C) #"],
    ["A) HyperText Markup Language", "B) HighTech Multimedia Language", "C) Hyperlink and Text Management Language"],
    ["A) Repeating a block of code until a condition is met", "B) Repeating a block of code a fixed number of times", "C) Making decisions based on conditions"],
    ["A) String", "B) Function", "C) Variable"],
    ["A) ^", "B) **", "C) %"],
    ["A) input()", "B) read()", "C) get_input()"],
    ["A) my_variable", "B) 2variable", "C) variable_2"],
    ["A) /", "B) //", "C) %"],
    ["A) 10", "B) 25", "C) 17"],
    ["A) List", "B) Dictionary", "C) Tuple"],
    ["A) The length of a string", "B) The number of elements in a list", "C) Both a and b"],
    ["A) require", "B) import", "C) include"],
    ["A) Removes an element from the list", "B) Adds an element to the end of the list", "C) Sorts the list in ascending order"],
    ["A) A high-level programming language", "B) A low-level programming language", "C) A markup language"],
    ["A) It requires explicit declaration of variables", "B) It is dynamically typed", "C) It is statically typed"],
    ["A) List", "B) Tuple", "C) Set"],
    ["A) P", "B) yth", "C) ytho"],
    ["A) python", "B) PYTHON", "C) PyThOn"],
    ["A) Terminates the program", "B) Skips execution to the next statement", "C) Does nothing"],
    ["A) my_var", "B) 123var", "C) _var"],
    ["A) 3.33", "B) 3", "C) 3.0"],
    ["A) /*", "B) #", "C) \"\"\""],
    ["A) 2", "B) 3", "C) -1"],
    ["A) Breaks out of the loop", "B) Skips the current iteration and proceeds to the next", "C) Halts the program execution"],
    ["A) True", "B) False", "C) None"],
    ["A) {1: 'one', 2: 'two'}", "B) [1: 'one', 2: 'two']", "C) (1: 'one', 2: 'two')"],
    ["A) python", "B) Python", "C) PYTHON"],
    ["A) list()", "B) strtolist()", "C) convert()"],
    ["A) Exponentiation", "B) Modulo division", "C) Floor division"],
    ["A) concat()", "B) merge()", "C) extend()"]
]

# Answers
answers = [1, 2, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2]
          